<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 ./TV.glb --transform
-->

<script>
	import { Group } from "three";
	import { T, forwardEventHandlers } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { tvPosition, tvRotation, tvScale } from "$lib/stores";

	export const ref = new Group();

	const gltf = useGltf("/models/TV-transformed.glb", { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={$tvPosition} rotation={$tvRotation} scale={$tvScale}>
			<T.Mesh geometry={gltf.nodes.Cube_1.geometry}>
				<T.MeshPhysicalMaterial color="#FF8A5B" metalness={0.8} roughness={0.7} />
			</T.Mesh>
			<T.Mesh geometry={gltf.nodes.Cube_2.geometry} material={gltf.materials.Screen} />
			<T.Mesh geometry={gltf.nodes.Cube_3.geometry} material={gltf.materials.Button} />
			<T.Mesh geometry={gltf.nodes.Cube_4.geometry} material={gltf.materials.disk} />
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
