<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 ./TV.glb --transform
-->

<script>
	import { Group } from "three";
	import { T, forwardEventHandlers } from "@threlte/core";
	import { useGltf } from "@threlte/extras";
	import { SheetObject } from "@threlte/theatre";

	export const ref = new Group();

	const gltf = useGltf("/models/TV-transformed.glb", { useDraco: true });

	const component = forwardEventHandlers();
</script>

<SheetObject key="TV">
	<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
		{#await gltf}
			<slot name="fallback" />
		{:then gltf}
			<T.Mesh
				geometry={gltf.nodes.Cube.geometry}
				material={gltf.nodes.Cube.material}
				position={[0, 0, 0]}
			/>
		{:catch error}
			<slot name="error" {error} />
		{/await}

		<slot {ref} />
	</T>
</SheetObject>
