<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 ./TV Foreground.glb --transform
-->

<script>
	import { Group } from "three";
	import { T, forwardEventHandlers } from "@threlte/core";
	import { useGltf } from "@threlte/extras";

	export const ref = new Group();

	const gltf = useGltf("/models/TV Foreground-transformed.glb", { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Cube002.geometry}
			material={gltf.nodes.Cube002.material}
			position={[0, 0, 0]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
